# Makefile for qi2txt, Linux version.
# Bruce Raup, 2010-06-25)
#

CC = gcc
FLAGS = -O

qi2txt: qi2txt.o
	$(CC) qi2txt.o -lm -o qi2txt

qi2gis_5.o: qi2txt.c
	$(CC) $(FLAGS) -c qi2txt.c

clean: 
	rm qi2txt.o
